[project]
name = "pydantic-ai-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "pydantic-ai>=0.1.9",
    "rich>=14.0.0",
]
